const express = require("express");
const app = express();
const cors = require("cors");
const { errors } = require("celebrate");
const routes = require("./routes/restrict.routes");
const freeRoutes = require("./routes/free.routes");
app.use(express.json());
app.use(freeRoutes);
app.use(routes);
app.use(errors());
module.exports = app;